# Generated by Django 3.1.5 on 2021-01-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza_firm', '0004_auto_20210128_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='cities',
            field=models.ManyToManyField(to='baza_firm.Company'),
        ),
        migrations.AddField(
            model_name='services',
            name='services',
            field=models.ManyToManyField(to='baza_firm.Company'),
        ),
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
