# Generated by Django 3.1.5 on 2021-01-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza_firm', '0006_auto_20210128_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.FloatField(choices=[('zdrowie', 'zdrowie'), ('marketing', 'marketing')])),
            ],
        ),
        migrations.RemoveField(
            model_name='services',
            name='services',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
    ]
