# Generated by Django 3.1.5 on 2021-01-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza_firm', '0012_auto_20210129_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryservices',
            name='service',
            field=models.FloatField(choices=[('zdrowie', 'zdrowie'), ('marketing', 'marketing')], null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact',
            field=models.EmailField(max_length=500),
        ),
    ]
