# Generated by Django 3.1.5 on 2021-01-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza_firm', '0013_auto_20210129_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='services',
            field=models.ManyToManyField(to='baza_firm.CategoryServices'),
        ),
        migrations.AlterField(
            model_name='categoryservices',
            name='service',
            field=models.CharField(default='', max_length=255),
        ),
    ]
