# Generated by Django 3.1.5 on 2021-01-29 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baza_firm', '0014_auto_20210129_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryservices',
            name='companies',
        ),
        migrations.RemoveField(
            model_name='company',
            name='services',
        ),
        migrations.AddField(
            model_name='company',
            name='services',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='baza_firm.categoryservices'),
        ),
    ]
