# Generated by Django 3.1.5 on 2021-01-31 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza_firm', '0019_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='author_name',
            field=models.CharField(blank=True, default='Anonim', max_length=50, null=True),
        ),
    ]
