# Generated by Django 3.1.5 on 2021-02-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza_firm', '0022_auto_20210201_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(blank=True, default='', max_length=50, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='login',
            new_name='username',
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.ManyToManyField(null=True, to='baza_firm.City'),
        ),
    ]
