# Generated by Django 3.1.5 on 2021-02-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza_firm', '0024_auto_20210201_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
