# Generated by Django 3.1.5 on 2021-02-01 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baza_firm', '0025_auto_20210201_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atribute', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password2',
        ),
        migrations.AddField(
            model_name='company',
            name='atribute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='baza_firm.atributes'),
        ),
    ]
