# Generated by Django 3.1.5 on 2021-02-01 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baza_firm', '0028_auto_20210201_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='atribute',
        ),
        migrations.AddField(
            model_name='company',
            name='atribute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='baza_firm.atributes'),
        ),
    ]
