# Generated by Django 3.1.5 on 2021-02-03 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baza_firm', '0032_auto_20210202_1935'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Atributes',
            new_name='Attributes',
        ),
    ]
