# Generated by Django 3.1.5 on 2021-02-03 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baza_firm', '0033_auto_20210203_1435'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attributes',
            new_name='AttributesCompany',
        ),
    ]
