# Generated by Django 3.1.5 on 2021-02-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza_firm', '0034_auto_20210203_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='atribute_comp',
            field=models.ManyToManyField(to='baza_firm.AttributesCompany'),
        ),
    ]
