# Generated by Django 3.1.5 on 2021-02-04 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baza_firm', '0035_auto_20210204_1148'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
