# Generated by Django 3.1.5 on 2021-02-04 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baza_firm', '0037_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
