# Generated by Django 3.1.5 on 2021-02-04 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baza_firm', '0038_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stationary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stationary_point', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='atribute_comp',
        ),
        migrations.AddField(
            model_name='company',
            name='have_stationary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='baza_firm.stationary'),
        ),
    ]
