# Generated by Django 3.1.5 on 2021-02-08 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baza_firm', '0039_auto_20210204_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='atribute_comp',
            field=models.ManyToManyField(to='baza_firm.AttributesCompany'),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_name',
            field=models.CharField(default='Brak danych', max_length=255),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.CharField(blank=True, default='Brak komentarza', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='have_stationary',
            field=models.ForeignKey(null='Brak danych', on_delete=django.db.models.deletion.CASCADE, to='baza_firm.stationary'),
        ),
        migrations.AlterField(
            model_name='stationary',
            name='stationary_point',
            field=models.CharField(default='Brak danych', max_length=500),
        ),
    ]
