# Generated by Django 3.1.5 on 2021-02-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza_firm', '0040_auto_20210208_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributescompany',
            name='atribute_choice',
            field=models.CharField(default='Brak danych', max_length=500),
        ),
    ]
