# Generated by Django 3.1.5 on 2021-01-26 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baza_firm', '0002_auto_20210126_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='company',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='company',
            name='nip',
        ),
        migrations.RemoveField(
            model_name='company',
            name='only_in_net',
        ),
        migrations.RemoveField(
            model_name='company',
            name='telephone',
        ),
    ]
