# Generated by Django 3.1.5 on 2021-01-28 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baza_firm', '0005_auto_20210128_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='cities',
            new_name='companies',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='name',
            new_name='name_service',
        ),
    ]
