# Generated by Django 3.1.5 on 2021-02-01 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baza_firm', '0027_auto_20210201_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atributes',
            old_name='atribute',
            new_name='atribute_choice',
        ),
    ]
