# Generated by Django 3.1.5 on 2021-02-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza_firm', '0030_auto_20210202_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='atribute',
            field=models.ManyToManyField(related_name='atrybuty', to='baza_firm.Atributes'),
        ),
    ]
